apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: time-mcp
  namespace: kagent
spec:
  transportType: stdio
  stdioTransport: {}
  deployment:
    image: mcp/time:latest
    cmd: /app/.venv/bin/mcp-server-time
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
